version: "3.7"
services:
  
  oncologypt_db:
    container_name: oncologypt_db
    restart: unless-stopped
    ports:
     - "3338:3306"
    build:
      context: ./
      dockerfile: docker-compose/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: oncologypt_mysql
    volumes:
      - oncologypt_mysql:/var/lib/mysql
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d

  oncologypt_app:
    build:
      args:
        user: duncan
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: oncologypt_app
    container_name: oncologypt_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
   
  oncologypt_nginx:
    container_name: oncologypt_nginx
    restart: unless-stopped
    ports:
      - 8096:80
    build:
        context: ./
        dockerfile: docker-compose/nginx/Dockerfile
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/:/etc/nginx/conf.d/

volumes:
  oncologypt_mysql: